/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.onurb.examples.avro.table1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TableRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5403098086990629869L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TableRecord\",\"namespace\":\"io.onurb.examples.avro.table1\",\"fields\":[{\"name\":\"table\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TableRecord> ENCODER =
      new BinaryMessageEncoder<TableRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TableRecord> DECODER =
      new BinaryMessageDecoder<TableRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TableRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TableRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TableRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TableRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TableRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TableRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TableRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TableRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence table;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TableRecord() {}

  /**
   * All-args constructor.
   * @param table The new value for table
   */
  public TableRecord(java.lang.CharSequence table) {
    this.table = table;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return table;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: table = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'table' field.
   * @return The value of the 'table' field.
   */
  public java.lang.CharSequence getTable() {
    return table;
  }


  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(java.lang.CharSequence value) {
    this.table = value;
  }

  /**
   * Creates a new TableRecord RecordBuilder.
   * @return A new TableRecord RecordBuilder
   */
  public static io.onurb.examples.avro.table1.TableRecord.Builder newBuilder() {
    return new io.onurb.examples.avro.table1.TableRecord.Builder();
  }

  /**
   * Creates a new TableRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TableRecord RecordBuilder
   */
  public static io.onurb.examples.avro.table1.TableRecord.Builder newBuilder(io.onurb.examples.avro.table1.TableRecord.Builder other) {
    if (other == null) {
      return new io.onurb.examples.avro.table1.TableRecord.Builder();
    } else {
      return new io.onurb.examples.avro.table1.TableRecord.Builder(other);
    }
  }

  /**
   * Creates a new TableRecord RecordBuilder by copying an existing TableRecord instance.
   * @param other The existing instance to copy.
   * @return A new TableRecord RecordBuilder
   */
  public static io.onurb.examples.avro.table1.TableRecord.Builder newBuilder(io.onurb.examples.avro.table1.TableRecord other) {
    if (other == null) {
      return new io.onurb.examples.avro.table1.TableRecord.Builder();
    } else {
      return new io.onurb.examples.avro.table1.TableRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for TableRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TableRecord>
    implements org.apache.avro.data.RecordBuilder<TableRecord> {

    private java.lang.CharSequence table;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.onurb.examples.avro.table1.TableRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.table)) {
        this.table = data().deepCopy(fields()[0].schema(), other.table);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing TableRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(io.onurb.examples.avro.table1.TableRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.table)) {
        this.table = data().deepCopy(fields()[0].schema(), other.table);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'table' field.
      * @return The value.
      */
    public java.lang.CharSequence getTable() {
      return table;
    }


    /**
      * Sets the value of the 'table' field.
      * @param value The value of 'table'.
      * @return This builder.
      */
    public io.onurb.examples.avro.table1.TableRecord.Builder setTable(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.table = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'table' field has been set.
      * @return True if the 'table' field has been set, false otherwise.
      */
    public boolean hasTable() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'table' field.
      * @return This builder.
      */
    public io.onurb.examples.avro.table1.TableRecord.Builder clearTable() {
      table = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TableRecord build() {
      try {
        TableRecord record = new TableRecord();
        record.table = fieldSetFlags()[0] ? this.table : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TableRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<TableRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TableRecord>
    READER$ = (org.apache.avro.io.DatumReader<TableRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.table);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.table = in.readString(this.table instanceof Utf8 ? (Utf8)this.table : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.table = in.readString(this.table instanceof Utf8 ? (Utf8)this.table : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










